public class AST implements Percentable
{
    private final String tag;
    private final Set<AST> asts;
    private final Set<Integer> hashes;
    private final Integer hashCode;
    private final Map<Integer, AST> fingerprints;

    // scoring heuristics
    public final Integer size;
    private final Integer depth;

    /**
     * Creates an AST with variadic children
     * 
     * @param tag the name/tag of the AST
     * @param children an array or variadic number of children
     */
    public AST(String tag, AST... children)
    {
        this(tag, Arrays.asList(children).stream());
    }

    /**
     * Creates an AST from a stream of children
     * 
     * @param tag the name/tag of the AST
     * @param children a stream containing children to add to the AST
     */
    public AST(String tag, Stream<AST> children)
    {
        this.tag = tag;
        this.asts = new HashSet<>();
        this.hashes = new HashSet<>();
        this.fingerprints = new HashMap<>();

        Monad<Integer> size = wrap(0);
        Monad<Integer> depth = wrap(0);

        children.forEach(A ->
        {
            asts.add(A);
            hashes.add(A.hashCode());
            size.set(unwrap(size) + A.size);
            depth.set(A.depth > unwrap(depth) ? A.depth : unwrap(depth));
        });

        this.size = unwrap(size) + 1;
        this.depth = unwrap(depth) + 1;
        hashCode = _hashCode();
    }

    /**
     * MUST BE CALLED AFTER GENERATION
     */
    public AST cacheFingerprinting()
    {
        fingerprint(wrap(fingerprints));
        return this;
    }

    /**
     * @return gets a mapping for all nodes in this tree of all fingerprints
     */
    public Map<Integer, AST> getFingerprints()
    {
        return Collections.unmodifiableMap(fingerprints);
    }

    /**
     * Store fingerprints in the provided Map
     * 
     * @param fpdb a monad of a map in which the fingerprints will be stored
     */
    public void fingerprint(final Monad<Map<Integer, AST>> fpdb)
    {
        AST t = unwrap(fpdb).put(hashCode(), this); // yes this may overwrite
                                                    // collisions
                                                    // no we do not care

        if (t != null && !tag.equals(t.tag) && !equals(t)) // OK maybe we do care...
        {
            System.out.println("HASH COLLISION!!!  mapsize(" + unwrap(fpdb).size() + ")");
            System.out.println("\t>"+tag);
            System.out.println("\t>"+t.tag);
        }

        asts.stream().forEach(A -> A.fingerprint(fpdb));
    }

    /**
     * given a mapping of another tree's fingerprints, generate a similarity
     * score
     * 
     * @param fpdb the map of the other tree's fingerprints
     * @return A percentage representing the amount of similarity between the
     *         two trees
     */
    public Real getPercentMatched(Map<Integer, AST> fpdb)
    {
        Real result = null;
        if (equals(fpdb.get(hashCode())))
        {
            result = new Real(size, size);
        } else
        {
            result = new Real(0, size);
        }

        for (AST t : asts)
        {
            result = result.scoreSummation(t.getPercentMatched(fpdb));
        }

        return result;
    }

    /*
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        return hashCode;
    }

    /*
     * AUTO GENERATED BY ECLIPSE
     * 
     * @see java.lang.Object#hashCode()
     */
    private int _hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((hashes == null) ? 0 : hashes.hashCode());
        result = prime * result + ((tag == null) ? 0 : tag.hashCode());
        return result;
    }

    /*
     * AUTO GENERATED BY ECLIPSE
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AST other = (AST) obj;
        if (hashes == null)
        {
            if (other.hashes != null)
                return false;
        } else if (!hashes.equals(other.hashes))
            return false;
        if (tag == null)
        {
            if (other.tag != null)
                return false;
        } else if (!tag.equals(other.tag))
            return false;
        return true;
    }

    @Override
    public Real getPercentageMatched()
    {
        throw new RuntimeException("cannot evaluate getPercentMatched()");
    }
}
